import type { Template } from "./editor-types";

export const templates: Template[] = [
  {
    id: "blank-post",
    name: "Blank Square",
    category: "Social",
    width: 1080,
    height: 1080,
    background: "#ffffff",
    elements: [],
  },
  {
    id: "sunset-quote",
    name: "Sunset Quote",
    category: "Social",
    width: 1080,
    height: 1080,
    background: "#ff6b6b",
    elements: [
      {
        type: "rect",
        x: 0, y: 0, width: 1080, height: 1080,
        fill: "#ff6b6b", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 380, width: 900,
        text: "Chase the\nsunset.",
        fontSize: 140, fontFamily: "Georgia", fontStyle: "bold",
        fill: "#fff8e7", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 780, width: 900,
        text: "— daily reminders",
        fontSize: 36, fontFamily: "Georgia", fontStyle: "italic",
        fill: "#fff8e7", align: "left",
        rotation: 0, opacity: 0.9, draggable: true,
      },
    ],
  },
  {
    id: "story-sale",
    name: "Flash Sale Story",
    category: "Story",
    width: 1080,
    height: 1920,
    background: "#0f172a",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1080, height: 1920,
        fill: "#0f172a", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "circle", x: 540, y: 700, radius: 380,
        fill: "#a855f7", stroke: "", strokeWidth: 0,
        rotation: 0, opacity: 0.9, draggable: true,
      },
      {
        type: "text", x: 90, y: 560, width: 900,
        text: "FLASH\nSALE",
        fontSize: 220, fontFamily: "Impact", fontStyle: "bold",
        fill: "#ffffff", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 1200, width: 900,
        text: "50% OFF everything",
        fontSize: 56, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#fde68a", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "presentation",
    name: "Presentation Slide",
    category: "Presentation",
    width: 1920,
    height: 1080,
    background: "#ffffff",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 640, height: 1080,
        fill: "#8b5cf6", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 80, y: 420, width: 480,
        text: "Ideas that\nship.",
        fontSize: 92, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#ffffff", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 760, y: 440, width: 1080,
        text: "A modern design studio for teams that move fast.",
        fontSize: 44, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#1f2937", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "poster-event",
    name: "Event Poster",
    category: "Print",
    width: 1200,
    height: 1600,
    background: "#111827",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1200, height: 1600,
        fill: "#111827", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 80, y: 80, width: 1040, height: 1440,
        fill: "", stroke: "#f59e0b", strokeWidth: 6, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 120, y: 220, width: 960,
        text: "NIGHT\nMARKET",
        fontSize: 220, fontFamily: "Impact", fontStyle: "bold",
        fill: "#f59e0b", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 120, y: 900, width: 960,
        text: "Saturday · 6pm – Midnight\nRiverside Park",
        fontSize: 44, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#ffffff", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "business-card",
    name: "Business Card",
    category: "Print",
    width: 1050,
    height: 600,
    background: "#f8fafc",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1050, height: 600,
        fill: "#f8fafc", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 0, y: 0, width: 12, height: 600,
        fill: "#7c3aed", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 180, width: 900,
        text: "Alex Rivera",
        fontSize: 72, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#0f172a", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 280, width: 900,
        text: "Product Designer",
        fontSize: 32, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#64748b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 460, width: 900,
        text: "alex@studio.co   ·   +1 555 010 2938",
        fontSize: 26, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#334155", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "cv-resume",
    name: "CV / Resume",
    category: "Print",
    width: 1200,
    height: 1600,
    background: "#ffffff",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 400, height: 1600,
        fill: "#1e293b", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 40, y: 80, width: 320,
        text: "JOHN DOE",
        fontSize: 56, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#ffffff", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 40, y: 160, width: 320,
        text: "Software Engineer",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#94a3b8", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 40, y: 300, width: 320,
        text: "CONTACT",
        fontSize: 24, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#ffffff", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 40, y: 350, width: 320,
        text: "john@example.com\n+1 234 567 8900\nNew York, USA",
        fontSize: 20, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#cbd5e1", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 460, y: 80, width: 680,
        text: "EXPERIENCE",
        fontSize: 32, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 460, y: 140, width: 680,
        text: "Senior Developer - Tech Corp\n2020 - Present\n- Led development of core products\n- Managed a team of 5 engineers",
        fontSize: 22, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#334155", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 460, y: 320, width: 680,
        text: "EDUCATION",
        fontSize: 32, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 460, y: 380, width: 680,
        text: "B.S. Computer Science - State University\n2016 - 2020",
        fontSize: 22, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#334155", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "report-card",
    name: "Student Report Card",
    category: "Print",
    width: 1200,
    height: 1600,
    background: "#f8fafc",
    elements: [
      {
        type: "text", x: 100, y: 80, width: 1000,
        text: "SPRINGFIELD HIGH SCHOOL",
        fontSize: 56, fontFamily: "Georgia", fontStyle: "bold",
        fill: "#1e293b", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 100, y: 160, width: 1000,
        text: "Official Academic Report Card",
        fontSize: 32, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#475569", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 100, y: 240, width: 1000, height: 4,
        fill: "#1e293b", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 100, y: 280, width: 500,
        text: "Student Name: Jane Smith",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 700, y: 280, width: 400,
        text: "Grade: 10th | Term: Fall",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#1e293b", align: "right",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 100, y: 360, width: 1000, height: 400,
        fill: "#ffffff", stroke: "#cbd5e1", strokeWidth: 2, cornerRadius: 8,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 140, y: 400, width: 300,
        text: "Subject",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 500, y: 400, width: 200,
        text: "Marks",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 800, y: 400, width: 200,
        text: "Grade",
        fontSize: 28, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#1e293b", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 140, y: 480, width: 900,
        text: "Mathematics                            95/100                            A\n\nScience                                   88/100                            B+\n\nEnglish Literature                    92/100                            A-\n\nHistory                                    85/100                            B\n\nPhysical Education                 98/100                            A+",
        fontSize: 24, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#334155", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      }
    ],
  },
];