import type { Template } from "./editor-types";

export const templates: Template[] = [
  {
    id: "blank-post",
    name: "Blank Square",
    category: "Social",
    width: 1080,
    height: 1080,
    background: "#ffffff",
    elements: [],
  },
  {
    id: "sunset-quote",
    name: "Sunset Quote",
    category: "Social",
    width: 1080,
    height: 1080,
    background: "#ff6b6b",
    elements: [
      {
        type: "rect",
        x: 0, y: 0, width: 1080, height: 1080,
        fill: "#ff6b6b", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 380, width: 900,
        text: "Chase the\nsunset.",
        fontSize: 140, fontFamily: "Georgia", fontStyle: "bold",
        fill: "#fff8e7", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 780, width: 900,
        text: "— daily reminders",
        fontSize: 36, fontFamily: "Georgia", fontStyle: "italic",
        fill: "#fff8e7", align: "left",
        rotation: 0, opacity: 0.9, draggable: true,
      },
    ],
  },
  {
    id: "story-sale",
    name: "Flash Sale Story",
    category: "Story",
    width: 1080,
    height: 1920,
    background: "#0f172a",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1080, height: 1920,
        fill: "#0f172a", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "circle", x: 540, y: 700, radius: 380,
        fill: "#a855f7", stroke: "", strokeWidth: 0,
        rotation: 0, opacity: 0.9, draggable: true,
      },
      {
        type: "text", x: 90, y: 560, width: 900,
        text: "FLASH\nSALE",
        fontSize: 220, fontFamily: "Impact", fontStyle: "bold",
        fill: "#ffffff", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 90, y: 1200, width: 900,
        text: "50% OFF everything",
        fontSize: 56, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#fde68a", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "presentation",
    name: "Presentation Slide",
    category: "Presentation",
    width: 1920,
    height: 1080,
    background: "#ffffff",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 640, height: 1080,
        fill: "#8b5cf6", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 80, y: 420, width: 480,
        text: "Ideas that\nship.",
        fontSize: 92, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#ffffff", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 760, y: 440, width: 1080,
        text: "A modern design studio for teams that move fast.",
        fontSize: 44, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#1f2937", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "poster-event",
    name: "Event Poster",
    category: "Print",
    width: 1200,
    height: 1600,
    background: "#111827",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1200, height: 1600,
        fill: "#111827", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 80, y: 80, width: 1040, height: 1440,
        fill: "", stroke: "#f59e0b", strokeWidth: 6, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 120, y: 220, width: 960,
        text: "NIGHT\nMARKET",
        fontSize: 220, fontFamily: "Impact", fontStyle: "bold",
        fill: "#f59e0b", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 120, y: 900, width: 960,
        text: "Saturday · 6pm – Midnight\nRiverside Park",
        fontSize: 44, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#ffffff", align: "center",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
  {
    id: "business-card",
    name: "Business Card",
    category: "Print",
    width: 1050,
    height: 600,
    background: "#f8fafc",
    elements: [
      {
        type: "rect", x: 0, y: 0, width: 1050, height: 600,
        fill: "#f8fafc", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "rect", x: 0, y: 0, width: 12, height: 600,
        fill: "#7c3aed", stroke: "", strokeWidth: 0, cornerRadius: 0,
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 180, width: 900,
        text: "Alex Rivera",
        fontSize: 72, fontFamily: "Helvetica", fontStyle: "bold",
        fill: "#0f172a", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 280, width: 900,
        text: "Product Designer",
        fontSize: 32, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#64748b", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
      {
        type: "text", x: 70, y: 460, width: 900,
        text: "alex@studio.co   ·   +1 555 010 2938",
        fontSize: 26, fontFamily: "Helvetica", fontStyle: "normal",
        fill: "#334155", align: "left",
        rotation: 0, opacity: 1, draggable: true,
      },
    ],
  },
];